look harder for snapback's config file

diff --git a/sbin/snapcrypt b/sbin/snapcrypt
--- a/sbin/snapcrypt
+++ b/sbin/snapcrypt
@@ -12,16 +12,25 @@ readonly -f abort abort-function abort-with-action-Usage
 readonly -f set-FS_label--from-mount_dir set-FS_type--from-path
 readonly -f merged-continuation-lines need-cmds
 
-for dir in ~/etc /usr/local/etc /etc
-    do	config_dir=$dir/$our_name
-	[[ -d $config_dir ]] && break
-done; readonly config_dir
-source $config_dir/configure.sh || abort "missing configure.sh"
+function set-config_file() {
+	local package=$1
+
+	local dir
+	for dir in ~/etc /usr/local/etc /etc
+	    do	config_file=$dir/$package/configure.sh
+		[[ -s $config_file ]] && return 0
+	done
+	return 1
+}
+
+set-config_file $our_name || abort "can't find our (non-empty) configure.sh"
+readonly config_dir=$(dirname  $config_file)
+source  $config_file || abort "$config_file doesn't end with 'true'"
 readonly udev_rules_file=$config_dir/drives.rules
-[[ -s $udev_rules_file ]] || abort "need non-empty $udev_rules_file"
+[[  -s  $udev_rules_file ]] || abort "need non-empty $udev_rules_file"
 
 # this sets common_mount_options, extN_mount_options, xfs_mount_options
-source  /etc/snapback/configure.sh &> /dev/null # optional
+set-config_file snapback && source $config_file
 
 # udev may not provide much of a PATH: https://unix.stackexchange.com/a/99073
 PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
